# Generated by Django 4.2 on 2026-03-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Savinggold', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
    ]
