# Generated by Django 4.2 on 2026-03-17 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Savinggold', '0002_saver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goldsaving',
            old_name='weight',
            new_name='gold_weight',
        ),
        migrations.RemoveField(
            model_name='goldsaving',
            name='member_name',
        ),
        migrations.AddField(
            model_name='goldsaving',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='goldsaving',
            name='saver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Savinggold.saver'),
        ),
        migrations.AddField(
            model_name='saver',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saver',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='saver',
            name='national_id',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='goldsaving',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='saver',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
